//! Minimal ldk-node wrapper for smite fuzzing.
//!
//! Uses bitcoind RPC as the backend, prints the node's pubkey on startup, and
//! waits for SIGTERM to shut down cleanly. Ignores all events generated by
//! ldk-node since we reset the VM after each fuzz iteration anyway.

use std::net::SocketAddr;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

use ldk_node::Builder;
use ldk_node::bitcoin::Network;

/// Signal handler sets this to true to trigger shutdown.
static SHUTDOWN: AtomicBool = AtomicBool::new(false);

/// Set by the SIGUSR1 handler. bitcoind's `-blocknotify` sends SIGUSR1 on each
/// new block so the main loop syncs immediately instead of waiting for the next
/// 2s chain poll.
static NEW_BLOCK: AtomicBool = AtomicBool::new(false);

extern "C" fn handle_signal(_: libc::c_int) {
    SHUTDOWN.store(true, Ordering::SeqCst);
}

extern "C" fn handle_block(_: libc::c_int) {
    NEW_BLOCK.store(true, Ordering::SeqCst);
}

fn main() {
    // Set up signal handlers for graceful shutdown
    unsafe {
        // Cast through pointer to satisfy Rust's function-to-integer cast rules
        let sighandler = handle_signal as *const () as libc::sighandler_t;
        libc::signal(libc::SIGTERM, sighandler);
        libc::signal(libc::SIGINT, sighandler);
        let blockhandler = handle_block as *const () as libc::sighandler_t;
        libc::signal(libc::SIGUSR1, blockhandler);
    }

    let args: Vec<String> = std::env::args().collect();
    if args.len() != 5 {
        eprintln!(
            "Usage: {} <data-dir> <listen-port> <bitcoind-rpc-port> <target-blockheight>",
            args[0]
        );
        std::process::exit(1);
    }

    let data_dir = args[1].clone();
    let listen_port: u16 = args[2].parse().expect("valid listen port");
    let rpc_port: u16 = args[3].parse().expect("valid RPC port");
    let target_blockheight: u32 = args[4].parse().expect("valid target blockheight");

    let listen_addr: SocketAddr = format!("0.0.0.0:{listen_port}")
        .parse()
        .expect("valid listen address");

    let node = Builder::new()
        .set_network(Network::Regtest)
        .set_chain_source_bitcoind_rpc(
            "127.0.0.1".to_string(),
            rpc_port,
            "rpcuser".to_string(),
            "rpcpass".to_string(),
        )
        .set_listening_addresses(vec![listen_addr.into()])
        .expect("valid listening addresses")
        .set_storage_dir_path(data_dir)
        .build()
        .expect("node build");

    node.start().expect("node start");

    // Wait for the chain to sync to the target blockheight before signaling
    // readiness. ldk-node polls bitcoind every 2 seconds, so this can take a
    // few seconds after startup.
    while node.status().current_best_block.height < target_blockheight {
        std::thread::sleep(Duration::from_secs(1));
    }

    // Output for LdkTarget to parse
    println!("PUBKEY:{}", node.node_id());
    println!("READY");

    // Wait for shutdown signal
    while !SHUTDOWN.load(Ordering::SeqCst) {
        // Sync the wallet whenever bitcoind signals a new block. ldk-node's own
        // 2s background poll keeps running, so this is technically redundant and
        // may race it, but that's safe: ldk-node coalesces concurrent syncs, so
        // whichever loses the race just waits on the in-flight sync's result
        // rather than applying the block twice. We accept the redundancy to sync
        // on the block instead of up to 2s later.
        if NEW_BLOCK.swap(false, Ordering::SeqCst)
            && let Err(e) = node.sync_wallets()
        {
            eprintln!("sync_wallets failed: {e}");
        }

        std::thread::sleep(Duration::from_millis(50));
    }

    node.stop().expect("node stop");
}
